export const START_LOADING_QUESTION_INFO = 'ui-question-info/ START LOADING QUESTION INFO';
export const FINISH_LOADING_QUESTION_INFO = 'ui-question-info/ FINISH LOADING QUESTION INFO';
export const ERROR_LOADING_QUESTION_INFO = 'ui-question-info/ ERROR LOADING QUESTION INFO';
