export const FETCH_CATEGORIES_SUCCESS = 'category/ FETCH CATEGORIES SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'category/ FETCH CATEGORIES FAIL';

export const CREATE_CATEGORY = 'category/ CREATE CATEGORY';
export const DELETE_CATEGORY = 'category/ DELETE CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'category/ EDIT CATEGORY SUCCESS';
