export const START_LOADING_SUGGESTIONS = 'ui/ START LOADING SUGGESTIONS';
export const FINISH_LOADING_SUGGESTIONS = 'ui/ FINISH LOADING SUGGESTIONS';
export const ERROR_LOADING_SUGGESTIONS = 'ui/ ERROR LOADING SUGGESTIONS';
export const START_LOADING_NEXT_SUGGESTIONS =
  'ui/ START LOADING NEXT SUGGESTIONS';
export const FINISH_LOADING_NEXT_SUGGESTIONS =
  'ui/ FINISH LOADING NEXT SUGGESTIONS';
export const ERROR_LOADING_NEXT_SUGGESTIONS =
  'ui/ ERROR LOADING NEXT SUGGESTIONS';
